homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.978924
  longitude: -118.465342
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 18
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# log everything
# https://www.home-assistant.io/components/logger/
logger:
  # default: debug
  # default: info
  default: info
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.homekit: debug
    pyhap: debug
    homeassistant.components.zwave: info

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

#ios app
ios:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
# automation: !include automations.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml

# ***************************************************************************
# Pushbullet notifications
# https://www.home-assistant.io/components/notify.pushbullet/
# ***************************************************************************

notify:
  # optional name for multiple services
  - platform: pushbullet
    name: pushbullet
    # api_key: o.4dvKIzH7D8PeeWwQazejtYLLikha4TxV
    api_key: !secret pushbullet_token

# ***************************************************************************
# Scenes
# NOTE: User scripts or mqtt -> node read automations instead
# ***************************************************************************

# scene:
#   - name: Morning scene
#     entities:
#       light.livingroom_lamp:
#         state: on
#         brightness_pct: 50
#       media_player.bedroom:
#         state: playing
#         volume_level: 0.30
#         source: KPCC
#       media_player.bathroom:
#         volume_level: 0.20
#       media_player.livingroom:
#         volume_level: 0.20
#   - name: Bedtime scene
#     entities:
#       light.livingroom_lamp:
#         state: on
#         brightness_pct: 50
#       light.bedroom_lamp_left:
#         state: on
#         brightness_pct: 50
#       light.bedroom_lamp_right:
#         state: on
#         brightness_pct: 50
#       media_player.bedroom:
#         state: playing
#         volume_level: 0.30
#         source: 'Blue Moon Revisited (Song For Elvis) Radio'
#       media_player.bathroom:
#         volume_level: 0.20
#       media_player.livingroom:
#         volume_level: 0.20

# ***************************************************************************
# Configurator
# ***************************************************************************

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: http://hassio.local:1880

# ***************************************************************************
# MQTT - for triggering and communicating with node-red flows
# ***************************************************************************

mqtt:
  broker: core-mosquitto

# ***************************************************************************
# Aeotec z-wave usb stick
# ***************************************************************************

zwave:
  usb_path: /dev/ttyACM0
  debug: true

# ***************************************************************************
# https://www.home-assistant.io/components/vera/
# ***************************************************************************
# vera:
#   vera_controller_url: http://192.168.7.186:3480/
#   # Optional to exclude devices - this is a list of vera device ids
#   # exclude: [ 13, 14, 16, 20, 23, 72, 73, 74, 75, 76, 77, 78, 88, 89, 99]
#   # Optional to import switches as lights - this is a list of vera device ids
#   lights: [5]

# Decora wifi dimmer plug
# light:
#   - platform: decora_wifi
#     username: mail@rishinyc.com
#     password: Leviton-truck-34

# ***************************************************************************
# Nest
# ***************************************************************************
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# ***************************************************************************
# Homekit
# NOTE: pass all devices through home-bridge instead
# https://www.home-assistant.io/components/homekit/
# ***************************************************************************
homekit:
  # see startup automations, will start on z-wave ready
  auto_start: false
  include_domains:
    - automation
    - climate
    # - device_tracker
    - input_boolean
    - light
    - script
    - media_player
  # include_entities:
    # - group.all_lights
    # - light.livingroom_lamp
    # - light.bedroom_lamp_left
    # - light.bedroom_lamp_right
  # exclude_entities:
    # - light.aeotec_zw099_smart_dimmer_6_level

# ***************************************************************************
# presence based on router network presence
# ***************************************************************************
device_tracker:
  - platform: nmap_tracker
    # iphone 7
    hosts: 192.168.7.22
    home_interval: 5
    exclude:
        # the ip of the raspi itself
        - 192.168.7.34

# ***************************************************************************
# grouped lights
# ***************************************************************************
light:
  - platform: group
    name: Bedroom lights
    entities:
      - light.bedroom_lamp_left
      - light.bedroom_lamp_right

# Dummy switch devices
input_boolean:
  kpcc_switch:
    name: KPCC
    initial: off
    icon: mdi:panda
  # for homekit based presence
  me_present:
    name: Me at home
    icon: mdi:account
