# #############################################################################
# ios location based on homekit automation
# #############################################################################
- alias: Notify on arrive home (Homekit)
  trigger:
    - platform: state
      entity_id: input_boolean.me_present
      from: 'off'
      to: 'on'
  condition: []
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: Arrived home
      message: Based on homekit automation
- alias: Notify on leave home (Homekit)
  trigger:
    - platform: state
      entity_id: input_boolean.me_present
      from: 'on'
      to: 'off'
  condition: []
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: Left home
      message: Based on homekit automation
# #############################################################################
# Router base leave/home notifications
# #############################################################################
- alias: Notify on Leave (Router)
  trigger:
  - platform: state
    entity_id: device_tracker.d4a33d298b4b
    from: home
    to: not_home
  condition: []
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: Left home
      message: Based on the router (entity device_tracker.d4a33d298b4b)
- alias: Notify on arrive (Router)
  trigger:
  - platform: state
    entity_id: device_tracker.d4a33d298b4b
    from: not_home
    to: home
  condition: []
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: Arrived home
      message: Based on the router (entity device_tracker.d4a33d298b4b)
