# #############################################################################
# Turn on lamp at sunset and at home
# #############################################################################
- alias: Turn on the livingroom lamp at sunset when at home
  initial_state: True
  hide_entity: False
  trigger:
    # platform: time
    # at: '19:13:00'
    platform: sun
    event: sunset
    offset: "-00:00:01"
  condition:
    # If home based on homekit automation switch
    # entity_id: input_boolean.me_present
    # condition: state
    # state: 'on'
    # If home based on homekit automation switch
    entity_id: device_tracker.d4a33d298b4b
    condition: state
    state: home
  action:
    service: light.turn_on
    entity_id: light.livingroom_lamp
    data:
      entity_id: light.livingroom_lamp
      brightness_pct: 50
# #############################################################################
# Turn on lamp when arrive home after sunset
# #############################################################################
- alias: Turn on the livingroom lamp when arrive home after dark (Homekit)
  trigger:
    # - platform: state
    #   entity_id: input_boolean.me_present
    #   from: 'off'
    #   to: 'on'
  - platform: state
    entity_id: device_tracker.d4a33d298b4b
    from: not_home
    to: home
  condition:
    condition: sun
    after: sunset
  action:
    - service: light.turn_on
      entity_id: light.livingroom_lamp
      data:
        entity_id: light.livingroom_lamp
        brightness_pct: 50
    - service: notify.ios_rishis_iphone_7
      data:
        title: Living room lamp on
        message: Turned on to 50%
