# #############################################################################
# Turn on Nest if its cold in the morning
# #############################################################################
# - alias: Turn on Nest if its cold in the morning
#   initial_state: True
#   hide_entity: False
#   trigger:
#     platform: time
#     at: '5:45'
#     # platform: sun
#     # event: sunset
#     # offset: "-00:00:01"
#   condition:
#     entity_id: sensor.nest_thermostat_temperature
#     condition: temperature
#     below: 70
#   action:
#     service: climate.set_temperature
#     entity_id: climate.nest
#     data:
#       entity_id: climate.nest
#       temperature: 72
#       operation_mode: Heat
