# #############################################################################
# Home assistant start/shutdown notifications
# #############################################################################

- alias: Home assistant notify
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: Server
      message: Started
  - service: notify.pushbullet
    data:
      message: Server started
      target: device/chrome

- alias: Home shutdown notify
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: Server
      message: Shutting down
  - service: notify.pushbullet
    data:
      message: Server shutting down
      target: device/chrome

# *****************************************************************************
# Z-wave network events
# *****************************************************************************
- alias: Zwave network start
  trigger:
  - platform: event
    event_type: zwave.network_start
  condition: []
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: Z-Wave network
      message: Starting
  - service: notify.pushbullet
    data:
      message: Z-Wave network starting
      target: device/chrome

- alias: Zwave network ready
  trigger:
  - platform: event
    event_type: zwave.network_ready
  condition: []
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: Z-Wave network
      message: Ready, starting Homekit
  - service: notify.pushbullet
    data:
      message: Z-Wave network starting, starting Homekit
      target: device/chrome
  - service: homekit.start
