# #############################################################################
# Home assistant startup/shutdown notifications
# #############################################################################

- alias: Home assistant startup notify
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: System
      message: Server started
  - service: notify.pushbullet
    data:
      message: Server started
      target: device/chrome

- alias: Home assistant shutdown notify
  trigger:
    platform: homeassistant
    event: shutdown
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: System
      message: Server shutting down...
  - service: notify.pushbullet
    data:
      message: Server shutting down...
      target: device/chrome

# *****************************************************************************
# Z-wave network events
# *****************************************************************************

- alias: Zwave network starting
  trigger:
    platform: event
    event_type: zwave.network_start
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: System
      message: Z-Wave network starting...
  - service: notify.pushbullet
    data:
      message: Z-Wave network starting...
      target: device/chrome

- alias: Zwave network ready
  trigger:
    platform: event
    event_type: zwave.network_ready
  action:
  - service: notify.ios_rishis_iphone_7
    data:
      title: System
      message: Z-Wave network ready... starting Homekit
  - service: notify.pushbullet
    data:
      message: Z-Wave network ready... starting Homekit
      target: device/chrome
  # start homekit after z-wave network is ready
  - service: homekit.start



# EOF
